displayName=GPU v2
author=markp
description=GPU renderer with a lightweight suite of graphical enhancements
tags=gpu,hd,fog,skybox,lighting,draw distance,retro,performance
version=1.0.0
plugins=com.gpuv2.GpuPlugin
build=standard
